### ISSUE TITLE
Do not create controllers

### ISSUE THREAD

**Issue by linksgo2011** [jcoppieters/cody#28] opened 2015-05-18 11:07 UTC
Error: ENOENT, no such file or directory 'd:\workspace\codydev\mysite\controller
s'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.<anonymous> (d:\workspace\codydev\mysite.js:50:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sylvainlap** [comment] 2015-05-18 16:56
I got the same error...

**Comment by linksgo2011** [comment] 2015-05-19 02:09
@sylvainlap  Add a directory

**Comment by ticup** [comment] 2015-05-19 07:26
You are both having this on windows, am i correct?

**Comment by sylvainlap** [comment] 2015-05-19 08:08
Nope, on Ubuntu 15.04.

**Comment by freele** [comment] 2015-05-19 21:54
I already had such error, first thing I did was copying all the controllers. But on the second thought I understood that it was exporting of your additional controllers. You can comment those block of code with errors until you add your custom controllers.

**Comment by jcoppieters** [comment] 2015-05-20 07:47
This happens because in create_site.js all directories are (should be) copied into the newly created project. However as "controllers" is empty, it is not copied...

[ to make a quick fix do a  mkdir ./[your project]/controllers ]

Can someone have a look at "var copyRecursiveSync = function(src, dest) { ... }" why it doesn't (or does) live up to its comment "Look ma, it's cp -R."  and change the code?

thanks, Johan.

**Comment by ticup** [comment] 2015-05-20 15:42
The problem is that git doesn't track empty directories by itself. So the empty directory was never in the repository in to start. [Stackoverflow Reference](http://stackoverflow.com/questions/3030230/does-git-ignore-empty-folders)

I added a "YourController.js" to controllers, which fixes this and also demonstrates the boilerplate code to make your own Controller.

Committed here 912380bec8c1e9e13aac8543e0fc01f79c9cd329 and published on npm as v3.3.17.

Thanks all for your input!

**Comment by jcoppieters** [comment] 2015-05-20 16:13
Did you remove my quick and dirty "mkdir controllers" in the create_site.js ?

**Comment by ticup** [comment] 2015-05-20 16:41
Now I did. Didn't know you hacked it ;)
We can wait till next version bump to push on into npm though, no harm.

**Closed by ticup** 2015-05-20 16:41 UTC
Labels: bug
